### ISSUE TITLE
.NET 8 GA / MudBlazor issues

### ISSUE THREAD

**Issue by linkdotnet** [linkdotnet/LINQMarbles#16]
Running the application locally after upgrading everything to .NET 8 GA leads to issues in combination with MudBlazor. 

Here the console log, after an upgrade and running the application:
```no-class
Error: One or more errors occurred. (The JSON value could not be converted to Microsoft.AspNetCore.Components.RootComponentOperation[]. Path: $ | LineNumber: 0 | BytePositionInLine: 1.)
    at Jn (marshal-to-js.ts:349:18)
    at Ul (marshal-to-js.ts:306:28)
    at 00b1e8b6:0x1faca
    at 00b1e8b6:0x1bf8b
    at 00b1e8b6:0xf172
    at 00b1e8b6:0x1e7e4
    at 00b1e8b6:0x1efda
    at 00b1e8b6:0xcfec
    at 00b1e8b6:0x440ad
    at e.<computed> (cwraps.ts:338:24)
```

Navigating to a new page:
<img width="1512" alt="image" src="https://github.com/linkdotnet/LINQMarbles/assets/26365461/bbf1bd96-7fc5-4a50-a2b8-bda6a8e1d55a">

Interactivity is completely broken - it seems I can't even click a button anymore. My best guess is to wait for MudBlazor `v7`.

**Assumption:** It is related to MudBlazor.

**Comment by linkdotnet** [comment]
Removing "obj" / "bin" helped - it was just caching issue
